from django.urls import path
from domain.views import (
    health,
    overview,
    api_list_activities,
    api_get_activity,
    api_create_activity,
    api_update_activity,
    api_publish_activity,
    api_cancel_activity,
    api_list_products,
    api_create_product,
    api_get_user_account,
    api_grab_flash_sale,
    api_pay_order,
    api_cancel_order,
    api_expire_overdue_orders,
    api_list_user_orders,
    api_get_winners,
    api_init_demo_data,
)

urlpatterns = [
    path("health", health),
    path("api/health", health),
    path("overview", overview),
    path("api/overview", overview),
    path("api/flash-sale/activities", api_list_activities),
    path("api/flash-sale/activities/<int:activity_id>", api_get_activity),
    path("api/flash-sale/activities/create", api_create_activity),
    path("api/flash-sale/activities/<int:activity_id>/update", api_update_activity),
    path("api/flash-sale/activities/<int:activity_id>/publish", api_publish_activity),
    path("api/flash-sale/activities/<int:activity_id>/cancel", api_cancel_activity),
    path("api/flash-sale/activities/<int:activity_id>/winners", api_get_winners),
    path("api/flash-sale/activities/<int:activity_id>/items/<int:item_id>/grab", api_grab_flash_sale),
    path("api/products", api_list_products),
    path("api/products/create", api_create_product),
    path("api/user/account", api_get_user_account),
    path("api/user/orders", api_list_user_orders),
    path("api/orders/<int:order_id>/pay", api_pay_order),
    path("api/orders/<int:order_id>/cancel", api_cancel_order),
    path("api/orders/expire-overdue", api_expire_overdue_orders),
    path("api/init-demo-data", api_init_demo_data),
]
