# Generated by Django 5.1.4 on 2026-06-07 13:29

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlashSaleActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('banner', models.URLField(blank=True)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('ongoing', '进行中'), ('ended', '已结束'), ('cancelled', '已取消')], default='draft', max_length=20)),
                ('created_by', models.CharField(default='admin', max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'flash_sale_activities',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.URLField(blank=True)),
                ('points_price', models.IntegerField(default=0)),
                ('original_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True)),
                ('user_name', models.CharField(max_length=100)),
                ('points_balance', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_accounts',
            },
        ),
        migrations.CreateModel(
            name='FlashSaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_points', models.IntegerField(default=0)),
                ('total_stock', models.IntegerField(default=0)),
                ('available_stock', models.IntegerField(default=0)),
                ('sold_count', models.IntegerField(default=0)),
                ('limit_per_user', models.IntegerField(default=1)),
                ('sort_order', models.IntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='domain.flashsaleactivity')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domain.product')),
            ],
            options={
                'db_table': 'flash_sale_items',
            },
        ),
        migrations.CreateModel(
            name='FlashSaleOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=50, unique=True)),
                ('user_id', models.CharField(max_length=100)),
                ('user_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('points_amount', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('locked', '已锁定待支付'), ('paid', '已支付'), ('cancelled', '已取消'), ('expired', '已过期')], default='locked', max_length=20)),
                ('locked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domain.flashsaleactivity')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domain.flashsaleitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='domain.product')),
            ],
            options={
                'db_table': 'flash_sale_orders',
                'indexes': [models.Index(fields=['user_id', 'activity_id'], name='flash_sale__user_id_84ba13_idx'), models.Index(fields=['status', 'locked_at'], name='flash_sale__status_5c6e1b_idx')],
            },
        ),
    ]
